"""
Query Request/Response Schemas
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict


class ForeignKey(BaseModel):
    """Foreign key relationship"""
    from_table: str = Field(..., description="Source table name")
    from_column: str = Field(..., description="Source column name")
    to_table: str = Field(..., description="Target table name")
    to_column: str = Field(..., description="Target column name")


class NL2SQLRequest(BaseModel):
    """Request for natural language to SQL conversion"""
    question: str = Field(..., description="Natural language question", min_length=1)
    db_schema: Dict[str, List[str]] = Field(
        ..., 
        description="Database schema as dictionary: {'table_name': ['col1', 'col2', ...]}",
        alias="schema"
    )
    foreign_keys: Optional[List[ForeignKey]] = Field(
        None, 
        description="Foreign key relationships (optional)"
    )
    use_sanitizer: bool = Field(
        True, 
        description="Whether to apply SQL validation and correction"
    )
    return_details: bool = Field(
        False, 
        description="Return detailed validation information"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "question": "How many users are from USA?",
                "schema": {
                    "users": ["id", "name", "email", "country"],
                    "orders": ["id", "user_id", "total", "created_at"]
                },
                "foreign_keys": [
                    {
                        "from_table": "orders",
                        "from_column": "user_id",
                        "to_table": "users",
                        "to_column": "id"
                    }
                ],
                "use_sanitizer": True,
                "return_details": False
            }
        }


class NL2SQLResponse(BaseModel):
    """Response from NL2SQL conversion"""
    sql: str = Field(..., description="Generated SQL query")
    question: str = Field(..., description="Original question")
    
    class Config:
        json_schema_extra = {
            "example": {
                "sql": "SELECT COUNT(*) FROM users WHERE country = 'USA'",
                "question": "How many users are from USA?"
            }
        }


class NL2SQLDetailedResponse(BaseModel):
    """Detailed response with validation information"""
    question: str = Field(..., description="Original question")
    raw_sql: str = Field(..., description="SQL generated by model (before correction)")
    corrected_sql: str = Field(..., description="SQL after sanitizer corrections")
    is_valid: bool = Field(..., description="Whether the SQL is valid")
    errors: List[str] = Field(..., description="List of errors/corrections applied")
    was_corrected: bool = Field(..., description="Whether any corrections were made")
    
    class Config:
        json_schema_extra = {
            "example": {
                "question": "How many users are from USA?",
                "raw_sql": "SELECT COUNT(*) FROM users WHERE Country = 'USA'",
                "corrected_sql": "SELECT COUNT(*) FROM users WHERE country = 'USA'",
                "is_valid": True,
                "errors": ["Fixed column case: 'Country' -> 'country'"],
                "was_corrected": True
            }
        }
