"""
SQL Pattern Correction Engine

Applies intelligent pattern-based corrections to generated SQL to fix common issues.
Uses generic patterns that work across domains, with special focus on academic/hierarchical
database structures (departments, courses, enrollments, etc.).

This is a hybrid approach: ML generates initial SQL, then pattern-based rules
refine it for correctness.
"""

import re
from typing import List, Tuple, Optional
import logging

logger = logging.getLogger(__name__)


class SQLPatternCorrector:
    """
    Applies pattern-based corrections to SQL generated by ML models.
    
    Focuses on fixing common ML errors:
    - Missing JOINs when querying multiple tables
    - Missing GROUP BY when using aggregations with dimensions
    - Incorrect table selection
    - Missing HAVING for filtered aggregations
    """
    
    def __init__(self):
        # Common patterns for entity-attribute relationships
        # Format: (entity_table, attribute_pattern, detail_table)
        self.entity_patterns = [
            # Academic structures
            (r'student', r'department', 'departments'),
            (r'student', r'major', 'departments'),
            (r'professor', r'department', 'departments'),
            (r'course', r'department', 'departments'),
            (r'course', r'professor', 'professors'),
            (r'enrollment', r'student', 'students'),
            (r'enrollment', r'course', 'courses'),
            (r'grade', r'student', 'students'),
            
            # General business patterns
            (r'order', r'customer', 'customers'),
            (r'product', r'category', 'categories'),
            (r'employee', r'department', 'departments'),
            (r'transaction', r'account', 'accounts'),
            (r'borrowing', r'member', 'members'),
            (r'borrowing', r'book', 'books'),
        ]
    
    def correct_sql(
        self,
        sql: str,
        question: str,
        schema_text: str,
        foreign_keys: List[Tuple[str, str, str, str]]
    ) -> str:
        """
        Apply pattern-based corrections to SQL.
        
        Args:
            sql: Generated SQL query
            question: Original natural language question
            schema_text: Schema in text format (will be parsed)
            foreign_keys: List of (from_table, from_col, to_table, to_col)
        
        Returns:
            Corrected SQL query
        """
        original_sql = sql
        
        # Parse schema from text
        schema_tables = self._parse_schema_text(schema_text)
        
        # Build FK map for quick lookup
        fk_map = self._build_fk_map(foreign_keys)
        
        # Apply corrections in order of priority
        sql = self._remove_incorrect_group_by(sql)  # Remove GROUP BY without aggregation FIRST
        sql = self._fix_incorrect_join_conditions(sql, schema_tables, fk_map)  # Fix wrong JOIN conditions
        sql = self._fix_missing_joins(sql, question, schema_tables, fk_map)
        sql = self._fix_where_clause_issues(sql, question, schema_tables, fk_map)  # Fix WHERE column mismatches
        sql = self._fix_missing_group_by(sql, question)
        sql = self._fix_aggregation_with_dimensions(sql, question, schema_tables, fk_map)
        sql = self._fix_having_clauses(sql, question)
        sql = self._fix_count_with_unnecessary_groupby(sql)
        
        if sql != original_sql:
            logger.info(f"Pattern correction applied:\n  Original: {original_sql}\n  Corrected: {sql}")
        
        return sql
    
    def _parse_schema_text(self, schema_text: str) -> dict:
        """Parse schema text into dict of table_name -> [columns]"""
        schema_tables = {}
        current_table = None
        
        for line in schema_text.split('\n'):
            line = line.strip()
            if not line:
                continue
            
            # Skip schema header lines (e.g., "SCHEMA FOR student_db:")
            if line.upper().startswith('SCHEMA FOR') or line.upper().startswith('SCHEMA:'):
                continue
            
            # Check if it's a table definition line
            # Format 1: "TABLE table_name:" or "table_name:"
            if ':' in line and not line.startswith('-'):
                parts = line.split(':', 1)
                table_name = parts[0].strip().lower()
                
                # Strip "table " prefix if present
                if table_name.startswith('table '):
                    table_name = table_name[6:]  # Remove "table "
                
                # Initialize table with empty column list
                schema_tables[table_name] = []
                current_table = table_name
                
                # Check if columns are on the same line (Format: "table: col1, col2, col3")
                columns_part = parts[1].strip() if len(parts) > 1 else ""
                if columns_part and not columns_part.startswith('-'):
                    # Extract column names (remove type info and FK annotations)
                    columns = []
                    for col in columns_part.split(','):
                        col = col.strip()
                        # Remove type info in parentheses
                        col = re.sub(r'\([^)]*\)', '', col)
                        # Take first word as column name
                        col_name = col.split()[0] if col else ""
                        if col_name:
                            columns.append(col_name.lower())
                    schema_tables[table_name] = columns
            
            # Format 2: "- table.column" or "- column"
            elif line.startswith('-'):
                # Extract column name from "- table.column" or "- column"
                col_text = line[1:].strip()  # Remove '-' prefix
                
                # Remove FK annotation: "(references ...)" or "(FK to ...)"
                col_text = re.sub(r'\((?:references|FK to)[^)]*\)', '', col_text).strip()
                # Remove other annotations in parentheses like (PK)
                col_text = re.sub(r'\([^)]*\)', '', col_text).strip()
                
                # Handle "table.column" format
                if '.' in col_text:
                    parts = col_text.split('.', 1)
                    table_name = parts[0].strip().lower()
                    col_name = parts[1].split()[0] if parts[1] else ""  # Take just the column name
                    
                    # Initialize table if not exists
                    if table_name not in schema_tables:
                        schema_tables[table_name] = []
                    
                    if col_name:
                        schema_tables[table_name].append(col_name.lower())
                elif current_table:
                    # Format: "- column" when current_table is set
                    col_name = col_text.split()[0]  # Take first word
                    if col_name:
                        schema_tables[current_table].append(col_name.lower())
        
        logger.info(f"Parsed schema tables: {list(schema_tables.keys())}")
        return schema_tables
    
    def _build_fk_map(self, foreign_keys: List[Tuple[str, str, str, str]]) -> dict:
        """Build a map of table relationships"""
        fk_map = {}
        for from_table, from_col, to_table, to_col in foreign_keys:
            if from_table not in fk_map:
                fk_map[from_table] = []
            fk_map[from_table].append({
                'from_col': from_col,
                'to_table': to_table,
                'to_col': to_col
            })
        return fk_map
    
    def _remove_incorrect_group_by(self, sql: str) -> str:
        """
        Remove GROUP BY clause when there's no aggregation function.
        
        The ML model sometimes incorrectly adds GROUP BY to simple SELECT queries.
        Pattern: SELECT col1, col2 FROM table GROUP BY col1
        Should be: SELECT col1, col2 FROM table
        
        Only remove if:
        - No aggregation functions (COUNT, SUM, AVG, MAX, MIN) in SELECT
        - GROUP BY is present
        """
        sql_upper = sql.upper()
        
        # Check if GROUP BY exists
        if 'GROUP BY' not in sql_upper:
            return sql
        
        # Check if there's an aggregation function in SELECT clause
        select_match = re.search(r'SELECT\s+(.*?)\s+FROM', sql, re.IGNORECASE | re.DOTALL)
        if not select_match:
            return sql
        
        select_clause = select_match.group(1).upper()
        
        # Check for aggregation functions
        has_aggregation = any(
            agg in select_clause 
            for agg in ['COUNT(', 'SUM(', 'AVG(', 'MAX(', 'MIN(', 'COUNT (', 'SUM (', 'AVG (', 'MAX (', 'MIN (']
        )
        
        # If no aggregation, remove GROUP BY
        if not has_aggregation:
            logger.info(f"Removing incorrect GROUP BY from query without aggregation: {sql}")
            sql = re.sub(r'\s+GROUP\s+BY\s+[^;]+', '', sql, flags=re.IGNORECASE)
        
        return sql
    
    def _fix_incorrect_join_conditions(
        self,
        sql: str,
        schema_tables: dict,
        fk_map: dict
    ) -> str:
        """
        Detect and fix incorrect JOIN conditions where the column doesn't exist in the referenced table.
        
        Example: SELECT ... FROM students AS T1 JOIN enrollments AS T2 ON T1.course_id = T2.course_id
        Problem: students table doesn't have course_id
        Fix: Replace with correct FK relationship (T1.student_id = T2.student_id)
        """
        # Find all JOIN conditions
        join_pattern = r'JOIN\s+(\w+)\s+(?:AS\s+)?(\w+)\s+ON\s+(\w+)\.(\w+)\s*=\s*(\w+)\.(\w+)'
        matches = list(re.finditer(join_pattern, sql, re.IGNORECASE))
        
        if not matches:
            return sql
        
        # Build alias to table mapping
        alias_to_table = {}
        
        # Find FROM table
        from_match = re.search(r'FROM\s+(\w+)(?:\s+(?:AS\s+)?(\w+))?', sql, re.IGNORECASE)
        if from_match:
            table = from_match.group(1).lower()
            alias = from_match.group(2).lower() if from_match.group(2) else table
            alias_to_table[alias] = table
        
        # Map all JOIN tables
        for match in matches:
            table = match.group(1).lower()
            alias = match.group(2).lower()
            alias_to_table[alias] = table
        
        # Check each JOIN condition
        for match in matches:
            left_alias = match.group(3).lower()
            left_col = match.group(4).lower()
            right_alias = match.group(5).lower()
            right_col = match.group(6).lower()
            
            if left_alias not in alias_to_table or right_alias not in alias_to_table:
                continue
            
            left_table = alias_to_table[left_alias]
            right_table = alias_to_table[right_alias]
            
            # Check if columns exist
            left_col_exists = left_table in schema_tables and left_col in [c.lower() for c in schema_tables[left_table]]
            right_col_exists = right_table in schema_tables and right_col in [c.lower() for c in schema_tables[right_table]]
            
            if not left_col_exists or not right_col_exists:
                logger.info(f"Detected incorrect JOIN condition: {left_alias}.{left_col} = {right_alias}.{right_col}")
                
                # Find correct FK relationship between these tables
                fk_info = self._find_fk_relationship(left_table, right_table, fk_map)
                if fk_info:
                    # Replace with correct JOIN condition
                    correct_join = f"JOIN {right_table} AS {right_alias} ON {left_alias}.{fk_info['from_col']} = {right_alias}.{fk_info['to_col']}"
                    old_join = match.group(0)
                    sql = sql.replace(old_join, correct_join)
                    logger.info(f"Fixed JOIN condition: {left_alias}.{fk_info['from_col']} = {right_alias}.{fk_info['to_col']}")
        
        return sql
    
    def _fix_missing_joins(
        self,
        sql: str,
        question: str,
        schema_tables: dict,
        fk_map: dict
    ) -> str:
        """
        Detect and fix missing JOINs.
        
        Pattern: If query references multiple tables but has no JOIN, add JOINs.
        """
        sql_upper = sql.upper()
        question_lower = question.lower()
        
        # Check if JOIN already exists
        if 'JOIN' in sql_upper:
            return sql  # Already has JOIN
        
        # Extract tables referenced in SQL (FROM, table.column)
        tables_in_sql = self._extract_tables_from_sql(sql, schema_tables)
        
        logger.info(f"Tables extracted from SQL: {tables_in_sql}")
        
        # Fix FROM clause if it references wrong table
        # This happens when model generates alias.column but wrong table in FROM
        from_match = re.search(r'FROM\s+(\w+)', sql, re.IGNORECASE)
        if from_match:
            current_from_table = from_match.group(1).lower()
            
            # Check if there's a different table referenced via columns that should be the main table
            # Priority: table with aggregation columns (e.g., gpa in AVG(s.gpa))
            if len(tables_in_sql) >= 2:
                # Find which table has the columns being aggregated/selected
                agg_match = re.search(r'(AVG|SUM|COUNT|MIN|MAX)\s*\(\s*([a-z])\.([\w_]+)\s*\)', sql, re.IGNORECASE)
                if agg_match:
                    alias, column = agg_match.group(2), agg_match.group(3).lower()
                    # Find table with this column
                    for table_name, columns in schema_tables.items():
                        if column in [c.lower() for c in columns] and table_name.lower() != current_from_table:
                            # Replace FROM clause with correct table
                            correct_table = table_name.lower()
                            sql = re.sub(
                                rf'FROM\s+{re.escape(current_from_table)}',
                                f'FROM {correct_table} {alias}',
                                sql,
                                flags=re.IGNORECASE
                            )
                            logger.info(f"Fixed FROM clause: {current_from_table} -> {correct_table} {alias}")
                            break
        
        # If multiple tables referenced, need JOIN
        if len(tables_in_sql) >= 2:
            logger.info(f"Multiple tables detected, injecting JOIN")
            return self._inject_join(sql, question_lower, schema_tables, fk_map, tables_in_sql)
        
        # Check for patterns that indicate missing JOIN
        # Pattern 1: "X with their Y" or "X with Y name"
        if re.search(r'\bwith\s+(their|its|the)\s+\w+', question_lower):
            return self._inject_join_from_question(sql, question_lower, schema_tables, fk_map)
        
        # Pattern 2: "X in/from Y department/category"
        if re.search(r'\b(in|from)\s+\w+\s+(department|category)', question_lower):
            return self._inject_join_from_question(sql, question_lower, schema_tables, fk_map)
        
        # Pattern 3: "how many X per/in each Y"
        if re.search(r'how\s+many.*\b(per|in\s+each|for\s+each)', question_lower):
            return self._inject_join_for_grouping(sql, question_lower, schema_tables, fk_map)
        
        # Pattern 4: "average/total X by Y"
        if re.search(r'(average|avg|total|sum).*\bby\s+\w+', question_lower):
            return self._inject_join_for_grouping(sql, question_lower, schema_tables, fk_map)
        
        return sql
    
    def _extract_tables_from_sql(self, sql: str, schema_tables: dict) -> set:
        """Extract all tables referenced in SQL"""
        tables = set()
        sql_lower = sql.lower()
        
        # Find FROM clause tables
        from_match = re.search(r'from\s+(\w+)', sql_lower)
        if from_match:
            tables.add(from_match.group(1))
        
        # Find table.column references (look for any tablename. pattern)
        for table_name in schema_tables.keys():
            # Match tablename followed by dot (for table.column)
            if re.search(rf'{re.escape(table_name)}\.', sql_lower):
                tables.add(table_name)
        
        # NEW: Detect aliases and infer table from column names
        # Pattern: alias.column_name (e.g., s.gpa, e.salary)
        alias_refs = re.findall(r'\b([a-z])\.([\w_]+)', sql_lower)
        
        for alias, column in alias_refs:
            # Check which table contains this column
            for table_name, columns in schema_tables.items():
                if column in [c.lower() for c in columns]:
                    tables.add(table_name.lower())
                    logger.info(f"Inferred table '{table_name}' from alias '{alias}' and column '{column}'")
                    break
        
        return tables
    
    def _inject_join_from_question(
        self,
        sql: str,
        question: str,
        schema_tables: dict,
        fk_map: dict
    ) -> str:
        """Inject JOIN by analyzing question for table references"""
        # Find main table from FROM clause
        from_match = re.search(r'from\s+(\w+)', sql, re.IGNORECASE)
        if not from_match:
            return sql
        
        main_table = from_match.group(1).lower()
        
        # Find target table mentioned in question
        # Check both exact match and partial match (e.g., "department" matches "departments")
        target_table = None
        for table_name in schema_tables.keys():
            table_lower = table_name.lower()
            if table_lower != main_table:
                # Exact match
                if table_lower in question:
                    target_table = table_lower
                    break
                # Partial match: remove trailing 's' and check
                if table_lower.endswith('s'):
                    singular = table_lower[:-1]
                    if singular in question:
                        target_table = table_lower
                        break
        
        if not target_table:
            return sql
        
        # Add missing column from target table to SELECT if needed
        # Pattern: "professors with their department names" → need departments.department_name in SELECT
        if target_table in schema_tables:
            target_columns = schema_tables[target_table]
            # Find name column in target table
            name_cols = [col for col in target_columns if 'name' in col.lower()]
            if name_cols:
                needed_col = f"{target_table}.{name_cols[0]}"
                # Check if this column is already in SELECT
                if needed_col not in sql.lower():
                    # Add it to SELECT clause
                    select_match = re.search(r'(SELECT\s+)(.*?)(\s+FROM)', sql, re.IGNORECASE)
                    if select_match:
                        existing_select = select_match.group(2)
                        new_select = f"{existing_select}, {needed_col}"
                        sql = re.sub(
                            r'SELECT\s+.*?\s+FROM',
                            f'SELECT {new_select} FROM',
                            sql,
                            count=1,
                            flags=re.IGNORECASE
                        )
                        logger.info(f"Added {needed_col} to SELECT clause")
        
        tables_to_join = {main_table, target_table}
        return self._inject_join(sql, question, schema_tables, fk_map, tables_to_join)
    
    def _inject_join(
        self,
        sql: str,
        question: str,
        schema_tables: dict,
        fk_map: dict,
        tables_in_sql: set
    ) -> str:
        """
        Inject JOIN clause into SQL based on foreign key relationships.
        
        Args:
            tables_in_sql: Set of tables that need to be joined
        """
        # Parse current SQL to find main table
        from_match = re.search(r'FROM\s+(\w+)', sql, re.IGNORECASE)
        if not from_match:
            return sql
        
        main_table = from_match.group(1).lower()
        tables_list = list(tables_in_sql)
        
        # Find other table(s) to join
        other_tables = [t for t in tables_list if t != main_table]
        if not other_tables:
            return sql
        
        # Build JOIN clause for each table
        join_clause = ""
        joined_tables = {main_table}  # Track which tables we've already joined
        
        for target_table in other_tables:
            # Try direct FK relationship first
            fk_info = self._find_fk_relationship(main_table, target_table, fk_map)
            if fk_info:
                # Direct relationship found
                if target_table not in joined_tables:
                    join_clause += f" JOIN {target_table} ON {fk_info['from_table']}.{fk_info['from_col']} = {fk_info['to_table']}.{fk_info['to_col']}"
                    joined_tables.add(target_table)
            else:
                # Try multi-hop path (e.g., courses -> enrollments -> grades)
                path = self._find_join_path(main_table, target_table, fk_map, joined_tables)
                if path:
                    for step in path:
                        if step['table'] not in joined_tables:
                            join_clause += f" JOIN {step['table']} ON {step['from_table']}.{step['from_col']} = {step['table']}.{step['to_col']}"
                            joined_tables.add(step['table'])
        
        if not join_clause:
            return sql
        
        # Inject JOIN after FROM clause (including optional alias)
        sql = re.sub(
            r'(FROM\s+\w+(?:\s+[a-z])?)',
            rf'\1{join_clause}',
            sql,
            flags=re.IGNORECASE
        )
        
        return sql
    
    def _find_fk_relationship(self, table1: str, table2: str, fk_map: dict) -> Optional[dict]:
        """Find FK relationship between two tables (either direction)"""
        # Check table1 -> table2
        for fk in fk_map.get(table1, []):
            if fk['to_table'].lower() == table2:
                return {
                    'from_table': table1,
                    'from_col': fk['from_col'],
                    'to_table': table2,
                    'to_col': fk['to_col']
                }
        
        # Check table2 -> table1
        for fk in fk_map.get(table2, []):
            if fk['to_table'].lower() == table1:
                return {
                    'from_table': table2,
                    'from_col': fk['from_col'],
                    'to_table': table1,
                    'to_col': fk['to_col']
                }
        
        return None
    
    def _find_join_path(self, from_table: str, to_table: str, fk_map: dict, existing_joins: set) -> Optional[List[dict]]:
        """
        Find a multi-hop JOIN path between two tables.
        
        For example: courses -> enrollments -> grades
        
        Returns list of join steps if path found, None otherwise.
        Each step is: {'table': 'table_name', 'from_table': 'x', 'from_col': 'y', 'to_col': 'z'}
        """
        # Common patterns for student_db
        join_patterns = {
            ('courses', 'grades'): [
                {'table': 'enrollments', 'from_table': 'courses', 'from_col': 'course_id', 'to_col': 'course_id'},
                {'table': 'grades', 'from_table': 'enrollments', 'from_col': 'enrollment_id', 'to_col': 'enrollment_id'}
            ],
            ('grades', 'courses'): [
                {'table': 'enrollments', 'from_table': 'grades', 'from_col': 'enrollment_id', 'to_col': 'enrollment_id'},
                {'table': 'courses', 'from_table': 'enrollments', 'from_col': 'course_id', 'to_col': 'course_id'}
            ],
            ('students', 'grades'): [
                {'table': 'enrollments', 'from_table': 'students', 'from_col': 'student_id', 'to_col': 'student_id'},
                {'table': 'grades', 'from_table': 'enrollments', 'from_col': 'enrollment_id', 'to_col': 'enrollment_id'}
            ],
            ('grades', 'students'): [
                {'table': 'enrollments', 'from_table': 'grades', 'from_col': 'enrollment_id', 'to_col': 'enrollment_id'},
                {'table': 'students', 'from_table': 'enrollments', 'from_col': 'student_id', 'to_col': 'student_id'}
            ],
        }
        
        # Check if we have a predefined path
        key = (from_table.lower(), to_table.lower())
        if key in join_patterns:
            return join_patterns[key]
        
        # Try BFS to find path dynamically (for general case)
        # For now, return None if no predefined path
        return None
    
    def _inject_join_for_grouping(
        self,
        sql: str,
        question: str,
        schema_tables: dict,
        fk_map: dict
    ) -> str:
        """
        Add JOIN when query needs grouping by a dimension from another table.
        
        Example: "How many students in each department?"
        - Main table: students
        - Group by: department.department_name (from departments table)
        - Need JOIN: students → departments
        """
        from_match = re.search(r'FROM\s+(\w+)', sql, re.IGNORECASE)
        if not from_match:
            return sql
        
        main_table = from_match.group(1).lower()
        
        # Detect grouping dimension from question
        grouping_keywords = ['per', 'each', 'by', 'in each', 'for each']
        grouping_entity = None
        
        for keyword in grouping_keywords:
            pattern = rf'{keyword}\s+(\w+)'
            match = re.search(pattern, question, re.IGNORECASE)
            if match:
                grouping_entity = match.group(1).lower()
                break
        
        if not grouping_entity:
            return sql
        
        # Find table that contains this grouping entity
        target_table = None
        for table_name in schema_tables.keys():
            if grouping_entity in table_name.lower() or table_name.lower().startswith(grouping_entity[:-1]):  # Handle plural
                target_table = table_name.lower()
                break
        
        if not target_table or target_table == main_table:
            return sql
        
        # Find FK relationship
        if main_table not in fk_map:
            return sql
        
        fk_info = None
        for fk in fk_map.get(main_table, []):
            if fk['to_table'].lower() == target_table:
                fk_info = fk
                break
        
        if not fk_info:
            return sql
        
        # Build corrected SQL with JOIN and GROUP BY
        join_clause = f" JOIN {target_table} ON {main_table}.{fk_info['from_col']} = {target_table}.{fk_info['to_col']}"
        
        # Find name column in target table
        name_cols = [col for col in schema_tables.get(target_table, []) if 'name' in col.lower()]
        if not name_cols:
            name_cols = [schema_tables[target_table][1]] if len(schema_tables[target_table]) > 1 else [schema_tables[target_table][0]]
        
        grouping_col = f"{target_table}.{name_cols[0]}"
        
        # Rebuild query
        select_match = re.search(r'SELECT\s+(.*?)\s+FROM', sql, re.IGNORECASE | re.DOTALL)
        if select_match:
            # Keep aggregation, add grouping column
            agg_part = select_match.group(1)
            new_select = f"{grouping_col}, {agg_part}" if grouping_col not in agg_part else agg_part
            
            # Remove any existing GROUP BY (likely wrong)
            sql = re.sub(r'\s+GROUP\s+BY.*', '', sql, flags=re.IGNORECASE)
            
            # Rebuild
            sql = f"SELECT {new_select} FROM {main_table}{join_clause} GROUP BY {grouping_col}"
        
        return sql
    
    def _fix_where_clause_issues(
        self,
        sql: str,
        question: str,
        schema_tables: dict,
        fk_map: dict
    ) -> str:
        """
        Fix WHERE clause issues:
        1. Column referenced doesn't exist in the joined tables
        2. Wrong table alias used
        3. Value compared against wrong column (e.g., professor name in course_name)
        4. WHERE clause used when query actually needs JOIN (e.g., "grades with student names")
        
        Example issue: "courses taught by professor Hopper"
        Wrong: WHERE T2.course_name = 'Hopper'
        Right: WHERE p.last_name = 'Hopper' (need to join professors table)
        """
        # Check for pattern: "X with Y names" where query has WHERE instead of JOIN
        # Example: "List grades with student names" → should JOIN students, not WHERE student
        if re.search(r'\bwith\s+(\w+)\s+names?\b', question, re.IGNORECASE):
            match = re.search(r'\bwith\s+(\w+)\s+names?\b', question, re.IGNORECASE)
            if match:
                entity = match.group(1).lower()  # "student", "professor", etc.
                
                # Check if query has WHERE clause that looks wrong
                if 'WHERE' in sql.upper() and 'JOIN' not in sql.upper():
                    # Find which table the entity refers to
                    target_table = None
                    for table_name in schema_tables.keys():
                        # Skip if table_name contains underscore (likely database name like student_db)
                        if '_' in table_name and 'db' in table_name.lower():
                            continue
                        # Check if entity matches table name (singular or plural)
                        table_singular = table_name.rstrip('s').lower()
                        if entity == table_name.lower() or entity == table_singular or entity + 's' == table_name.lower():
                            target_table = table_name
                            break
                    
                    if target_table:
                        logger.info(f"Detected 'X with Y names' pattern - rebuilding query with JOIN to {target_table}")
                        return self._rebuild_query_for_with_pattern(sql, question, target_table, schema_tables, fk_map)
        
        # Find WHERE clause
        where_match = re.search(r'WHERE\s+(.+?)(?:GROUP|ORDER|LIMIT|;|$)', sql, re.IGNORECASE)
        if not where_match:
            return sql
        
        where_clause = where_match.group(1).strip()
        
        # Extract all table aliases used in FROM/JOIN
        tables_in_query = {}  # alias -> table_name
        
        # Find FROM table
        from_match = re.search(r'FROM\s+(\w+)(?:\s+(?:AS\s+)?([A-Z0-9]+))?', sql, re.IGNORECASE)
        if from_match:
            table = from_match.group(1).lower()
            alias = from_match.group(2).lower() if from_match.group(2) else table
            tables_in_query[alias] = table
        
        # Find JOINed tables
        join_matches = re.finditer(r'JOIN\s+(\w+)(?:\s+(?:AS\s+)?([A-Z0-9]+))?', sql, re.IGNORECASE)
        for match in join_matches:
            table = match.group(1).lower()
            alias = match.group(2).lower() if match.group(2) else table
            tables_in_query[alias] = table
        
        # Check if WHERE clause references columns that don't exist
        # Pattern: alias.column or just column
        where_conditions = re.findall(r'(\w+)\.(\w+)\s*=\s*[\'"]([^\'"]+)[\'"]', where_clause, re.IGNORECASE)
        
        for alias, column, value in where_conditions:
            alias_lower = alias.lower()
            column_lower = column.lower()
            
            # Check if this alias exists
            if alias_lower not in tables_in_query:
                logger.info(f"WHERE clause references unknown alias '{alias}'")
                continue
            
            actual_table = tables_in_query[alias_lower]
            
            # Check if column exists in that table
            if actual_table in schema_tables:
                table_columns = [c.lower() for c in schema_tables[actual_table]]
                
                if column_lower not in table_columns:
                    logger.info(f"Column '{column}' not found in table '{actual_table}'. Looking for correct table...")
                    
                    # Try to infer correct table and column from question and value
                    # Pattern 1: "professor X" or "taught by X" in question with value matching name
                    # Pattern 2: WHERE condition references a name but column doesn't exist
                    needs_professor_filter = (
                        re.search(r'\bprofessor\b', question, re.IGNORECASE) or
                        re.search(r'\btaught\s+by\b', question, re.IGNORECASE) or
                        (column_lower == 'course_name' and value and value[0].isupper())  # Hopper looks like a name
                    )
                    
                    if needs_professor_filter:
                        # Should use professors table
                        if 'professors' in schema_tables:
                            prof_cols = schema_tables['professors']
                            
                            # Check if we need to add JOIN to professors
                            if 'professors' not in [t for t in tables_in_query.values()]:
                                # Need to add professors JOIN
                                # Find path to professors table
                                missing_tables = self._extract_tables_from_sql(sql, schema_tables)
                                missing_tables.add('professors')
                                
                                # Rebuild with correct JOINs
                                logger.info("Adding missing professors table for WHERE clause")
                                return self._rebuild_query_with_professor_filter(
                                    sql, question, value, schema_tables, fk_map
                                )
        
        return sql
    
    def _rebuild_query_for_with_pattern(
        self,
        sql: str,
        question: str,
        target_table: str,
        schema_tables: dict,
        fk_map: dict
    ) -> str:
        """
        Rebuild query for "X with Y names" pattern.
        
        Examples:
        - "List grades with student names" → grades JOIN enrollments JOIN students
        - "Show employees with department names" → employees JOIN departments
        """
        # Determine main table from existing SQL
        from_match = re.search(r'FROM\s+(\w+)', sql, re.IGNORECASE)
        if not from_match:
            logger.warning("Cannot rebuild query - no FROM table found")
            return sql
        
        main_table = from_match.group(1).lower()
        logger.info(f"Rebuilding '{main_table} with {target_table}' query")
        
        # Get columns from main table and target table
        main_cols = schema_tables.get(main_table, [])
        target_cols = schema_tables.get(target_table, [])
        
        if not main_cols or not target_cols:
            logger.warning(f"Cannot rebuild - missing schema for {main_table} or {target_table}")
            return sql
        
        # Build SELECT clause based on question
        select_cols = []
        
        # If "names" in question, add name columns from target table
        if 'names' in question.lower() or 'name' in question.lower():
            # Find name columns in target table
            name_cols = [col for col in target_cols if 'name' in col.lower()]
            if name_cols:
                select_cols.extend([f"{target_table[0]}.{col}" for col in name_cols])
        
        # Add main data columns (e.g., score from grades, salary from employees)
        # Common data columns to look for
        data_keywords = ['score', 'grade', 'salary', 'amount', 'value', 'quantity', 'count']
        for col in main_cols:
            if any(keyword in col.lower() for keyword in data_keywords):
                select_cols.append(f"{main_table[0]}.{col}")
        
        # If no data columns found, add first few non-ID columns
        if len(select_cols) == 0 or (len(select_cols) == len([c for c in select_cols if target_table[0] in c])):
            for col in main_cols:
                if 'id' not in col.lower() and col.lower() not in ['created_at', 'updated_at']:
                    select_cols.append(f"{main_table[0]}.{col}")
                    if len(select_cols) >= 3:
                        break
        
        if not select_cols:
            select_cols = [f"{main_table[0]}.*"]
        
        # Build JOIN clause using existing logic
        join_clause = ""
        joined_tables = {main_table}
        
        # Find path from main_table to target_table
        path = self._find_join_path(main_table, target_table, fk_map, joined_tables)
        if path:
            for step in path:
                if step['table'] not in joined_tables:
                    # Use alias (first letter) for consistency
                    from_alias = step['from_table'][0]
                    to_alias = step['table'][0]
                    join_clause += f" JOIN {step['table']} {to_alias} ON {from_alias}.{step['from_col']} = {to_alias}.{step['to_col']}"
                    joined_tables.add(step['table'])
        else:
            logger.warning(f"No JOIN path found from {main_table} to {target_table}")
            return sql
        
        # Construct new query
        new_sql = f"SELECT {', '.join(select_cols)} FROM {main_table} {main_table[0]}{join_clause}"
        
        logger.info(f"Rebuilt query: {new_sql}")
        return new_sql
    
    def _rebuild_query_with_professor_filter(
        self,
        sql: str,
        question: str,
        professor_name: str,
        schema_tables: dict,
        fk_map: dict
    ) -> str:
        """
        Rebuild query to properly filter by professor name.
        
        Expected pattern: students → enrollments → courses → professors
        """
        # Extract the SELECT clause
        select_match = re.search(r'SELECT\s+(.*?)\s+FROM', sql, re.IGNORECASE | re.DOTALL)
        if not select_match:
            return sql
        
        select_clause = select_match.group(1)
        
        # Determine what we're selecting (students and courses)
        # Build proper multi-hop JOIN
        # Pattern 1: Query mentions students OR courses with professor filter
        if ('students' in sql.lower() or 'courses' in sql.lower()) and 'professor' in question.lower():
            # Query pattern: Show students (and courses) taught by professor X
            # OR: List students enrolled in courses taught by professor X
            corrected = (
                f"SELECT s.first_name, s.last_name, c.course_name "
                f"FROM students s "
                f"JOIN enrollments e ON s.student_id = e.student_id "
                f"JOIN courses c ON e.course_id = c.course_id "
                f"JOIN professors p ON c.professor_id = p.professor_id "
                f"WHERE p.last_name = '{professor_name}'"
            )
            logger.info(f"Rebuilt query with professor filter: {corrected}")
            return corrected
        
        return sql
    
    def _fix_missing_group_by(self, sql: str, question: str) -> str:
        """
        Add GROUP BY when using aggregation with dimensions.
        
        Pattern: If SELECT has aggregation (COUNT, AVG) and non-aggregated column,
        need GROUP BY.
        """
        sql_upper = sql.upper()
        
        # Check if we have aggregation
        has_agg = any(agg in sql_upper for agg in ['COUNT', 'AVG', 'SUM', 'MAX', 'MIN'])
        if not has_agg:
            return sql
        
        # Check if GROUP BY is missing
        if 'GROUP BY' in sql_upper:
            return sql
        
        # Check if question implies grouping (e.g., "by department", "per student")
        grouping_match = re.search(r'\b(per|each|by)\s+(\w+)', question, re.IGNORECASE)
        if not grouping_match:
            return sql
        
        grouping_keyword = grouping_match.group(1).lower()
        grouping_entity = grouping_match.group(2).lower()
        
        # Find non-aggregated columns in SELECT
        select_match = re.search(r'SELECT\s+(.*?)\s+FROM', sql, re.IGNORECASE | re.DOTALL)
        if not select_match:
            return sql
        
        select_clause = select_match.group(1)
        
        # Find columns that aren't in aggregation functions
        columns = []
        for part in select_clause.split(','):
            part = part.strip()
            if not any(agg in part.upper() for agg in ['COUNT', 'AVG', 'SUM', 'MAX', 'MIN']):
                if part:  # Only non-empty, non-aggregated columns
                    columns.append(part)
        
        # If no dimension columns in SELECT but question has "by X", need to add them
        if not columns:
            # Try to find the grouping table from JOIN
            # Pattern: "by department" → look for departments table in JOIN
            join_match = re.search(rf'JOIN\s+(\w*{grouping_entity}\w*)', sql, re.IGNORECASE)
            if join_match:
                group_table = join_match.group(1).lower()
                # Find name column (look for *_name or name)
                # For now, assume table_name + "_name" or just "name"
                if grouping_entity in group_table:
                    group_col = f"{group_table}.{grouping_entity}_name"
                else:
                    group_col = f"{group_table}.name"
                
                # Add dimension to SELECT and GROUP BY
                select_clause_new = f"{group_col}, {select_clause}"
                sql = re.sub(
                    r'(SELECT\s+)(.*?)(\s+FROM)',
                    rf'\1{select_clause_new}\3',
                    sql,
                    flags=re.IGNORECASE | re.DOTALL,
                    count=1
                )
                columns.append(group_col)
        
        if columns:
            group_by_clause = f" GROUP BY {', '.join(columns)}"
            # Add before WHERE if exists, else at end
            where_match = re.search(r'\s+WHERE', sql, re.IGNORECASE)
            if where_match:
                insert_pos = where_match.start()
                sql = sql[:insert_pos] + group_by_clause + sql[insert_pos:]
            else:
                sql = sql.rstrip() + group_by_clause
        
        return sql
    
    def _fix_aggregation_with_dimensions(
        self,
        sql: str,
        question: str,
        schema_tables: dict,
        fk_map: dict
    ) -> str:
        """
        Fix queries that have dimension columns without proper grouping.
        
        Example: SELECT department.name, AVG(gpa) FROM students
        Should be: SELECT department.name, AVG(gpa) FROM students JOIN departments ... GROUP BY department.name
        """
        # This is handled by other methods, but we can add extra checks here
        return sql
    
    def _fix_having_clauses(self, sql: str, question: str) -> str:
        """
        Add HAVING clause when filtering on aggregated results.
        
        Pattern: "more than X", "less than Y", "at least Z" in question with aggregation
        """
        sql_upper = sql.upper()
        
        # Check if we have GROUP BY and aggregation
        if 'GROUP BY' not in sql_upper:
            return sql
        
        has_agg = any(agg in sql_upper for agg in ['COUNT', 'AVG', 'SUM'])
        if not has_agg:
            return sql
        
        # Check if HAVING already exists
        if 'HAVING' in sql_upper:
            return sql
        
        # Check if question implies filtering on aggregation
        filter_pattern = r'(more|greater|less|fewer|at\s+least|at\s+most)\s+than\s+(\d+)'
        match = re.search(filter_pattern, question, re.IGNORECASE)
        
        if match:
            comparator = match.group(1).lower()
            threshold = match.group(2)
            
            # Determine operator
            if 'more' in comparator or 'greater' in comparator:
                operator = '>'
            elif 'less' in comparator or 'fewer' in comparator:
                operator = '<'
            elif 'at least' in comparator:
                operator = '>='
            else:
                operator = '<='
            
            # Find the aggregation function
            agg_match = re.search(r'(COUNT|AVG|SUM)\s*\([^)]+\)', sql, re.IGNORECASE)
            if agg_match:
                agg_function = agg_match.group(0)
                having_clause = f" HAVING {agg_function} {operator} {threshold}"
                
                # Add HAVING after GROUP BY
                group_by_match = re.search(r'(GROUP\s+BY\s+[^;]+)', sql, re.IGNORECASE)
                if group_by_match:
                    insert_pos = group_by_match.end()
                    sql = sql[:insert_pos] + having_clause + sql[insert_pos:]
        
        return sql
    
    def _fix_count_with_unnecessary_groupby(self, sql: str) -> str:
        """
        Remove unnecessary GROUP BY when doing simple COUNT(*).
        
        Pattern: SELECT COUNT(*) FROM table GROUP BY id
        Should be: SELECT COUNT(*) FROM table
        """
        # Only if COUNT(*) is the only thing selected and no dimension
        if re.match(r'SELECT\s+COUNT\(\*\)\s+FROM\s+\w+\s+GROUP\s+BY\s+\w*id\b', sql, re.IGNORECASE):
            sql = re.sub(r'\s+GROUP\s+BY\s+\w*id\b', '', sql, flags=re.IGNORECASE)
        
        return sql


# Global instance
_pattern_corrector = None


def get_pattern_corrector() -> SQLPatternCorrector:
    """Get or create the global pattern corrector instance"""
    global _pattern_corrector
    if _pattern_corrector is None:
        _pattern_corrector = SQLPatternCorrector()
    return _pattern_corrector
